version: '2'
services:
  web:
    build: .
    image: richdkick/kickfolio
    container_name: kickfolio
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/app/project/app
      - ./public:/var/app/project/public
      - ./scss:/var/app/project/scss
      - ./test:/var/app/project/test
    depends_on:
      - db
    command: npm run start:dev
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: D0ck3R-r00T
    volumes:
      - ./mysql/.:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    ports:
      - "3306:3306"
